### PR TITLE
FEATURE: Translate backend module

### PR DESCRIPTION
**Pull request by crydotsnake**

### CODE REVIEW

**Review by crydotsnake — COMMENTED** [review]
Hello @bwaidelich 👋🏽 

I was not sure in a few places what I could use here as a translation:

- `Cron expression` line `9`
- `Handler class` line `34`
- `Workload` line `39`

Do you have any idea what we could use here as a German translation?

**Comment by crydotsnake** [comment]
Hi @bwaidelich 

I thought again, and I'm not sure if we should translate the whole module. Because maybe there are terms that are better explained in English than in German. How do you see that? 

And i need to update the PR again. I don't know why, but PHPStorm broke the formatting. Do I have to change something somewhere?

**Comment by bwaidelich** [comment]
Hey,

sorry for the late reaction, I missed this one for some reason.

> I thought again, and I'm not sure if we should translate the whole module [...] How do you see that?

I agree. It's a rather technical module anyways not targeted for editors really. But your translations will still be helpful of course, so thanks for that!
I would suggest to just leave out the technical terms (e.g. "Cron expression" is the correct term and it doesn't need an awkward translation like "Cron Ausdruck")

> And i need to update the PR again

What do you mean by that?
I can just merge it as-is!?

**Comment by crydotsnake** [comment]
> sorry for the late reaction, I missed this one for some reason.

No problem! 🙂 

> I would suggest to just leave out the technical terms (e.g. "Cron expression" is the correct term and it doesn't need an awkward translation like "Cron Ausdruck")

Yes, i agree with you! 🙂 

> What do you mean by that?
It was just one line, that wasnt formatted correctly. But i fixed it!

So if everything looks okay for you, you can merge the PR!

**Comment by bwaidelich** [comment]
Thank you, Simon!

**Pull request merged**
